defmodule Orbit.Auth.PasswordTest do
  use ExUnit.Case, async: true

  alias Orbit.Auth.Password

  # PHC hashes generated by argon2-cffi (PasswordHasher defaults) inside the
  # running python backend container — the exact format sitting in the users
  # table. Regenerate with:
  #
  #   docker exec -i dashboard-backend-1 python -c "
  #   from argon2 import PasswordHasher; h = PasswordHasher()
  #   print(h.hash('orbit-test-password-123')); print(h.hash('ümläut-pässwörd-🔥'))"
  @python_vectors [
    {"orbit-test-password-123",
     "$argon2id$v=19$m=65536,t=3,p=4$sKgHN47DV9/WpZ69epvrXQ$sy1rVDnHmcEig57BvMe/kMCzeB2r8pbYUQEzN/Zg+Yw"},
    {"ümläut-pässwörd-🔥",
     "$argon2id$v=19$m=65536,t=3,p=4$wld4t6uDvcx3BY6KPObGqA$q6uio91dWQirQ/l5lwPyOKi4R0LQguGozmQBxrYdALU"}
  ]

  describe "argon2-cffi interop" do
    test "verifies hashes produced by the python backend" do
      for {password, hash} <- @python_vectors do
        assert Password.verify(password, hash)
        refute Password.verify(password <> "x", hash)
      end
    end
  end

  describe "roundtrip" do
    test "own hash verifies and is argon2id PHC format" do
      hash = Password.hash("fresh-password")
      assert String.starts_with?(hash, "$argon2id$v=19$")
      assert Password.verify("fresh-password", hash)
      refute Password.verify("wrong", hash)
    end
  end

  describe "hardening" do
    test "nonexistent account (nil hash) returns false after a dummy verify" do
      refute Password.verify_constant_time("whatever", nil)
    end

    test "existing hash goes through normal verification" do
      {password, hash} = hd(@python_vectors)
      assert Password.verify_constant_time(password, hash)
    end

    test "malformed hash reads as wrong password, never raises" do
      refute Password.verify("pw", "not-a-phc-string")
      refute Password.verify("pw", "$argon2id$v=19$broken")
      refute Password.verify("pw", "")
    end
  end
end
