defmodule Orbit.Auth.TOTPTest do
  use ExUnit.Case, async: true

  alias Orbit.Auth.TOTP

  # Cross-language vectors generated by the backend's stdlib totp.py
  # (app.auth.totp._hotp) inside the running backend container. Regenerate:
  #
  #   docker exec -i dashboard-backend-1 python -c "
  #   import sys; sys.path.insert(0, '/app/src')
  #   from app.auth.totp import _hotp
  #   s = 'JBSWY3DPEHPK3PXPJBSWY3DPEHPK3PXP'
  #   for at in [0, 59, 1111111109, 1234567890, 2000000000, 1752717600]:
  #       print(at, _hotp(s, at // 30))"
  @secret "JBSWY3DPEHPK3PXPJBSWY3DPEHPK3PXP"
  @vectors [
    {0, "702218"},
    {59, "503347"},
    {1_111_111_109, "088309"},
    {1_234_567_890, "401544"},
    {2_000_000_000, "978524"},
    {1_752_717_600, "283562"}
  ]

  describe "python totp.py interop" do
    test "codes match the backend implementation at fixed timestamps" do
      for {at, code} <- @vectors do
        assert TOTP.verify(@secret, code, at: at, window: 0),
               "code #{code} at #{at} must verify"
      end
    end
  end

  describe "drift window" do
    test "accepts the previous/next step within window 1 (python parity)" do
      {at, _} = List.keyfind(@vectors, 1_234_567_890, 0)
      {_, prev_code} = List.keyfind(@vectors, 1_234_567_890, 0)
      # previous step code: verify code minted at `at` against a clock 30s later
      assert TOTP.verify(@secret, prev_code, at: at + 30, window: 1)
      refute TOTP.verify(@secret, prev_code, at: at + 60, window: 1)
    end
  end

  describe "input hygiene" do
    test "rejects malformed codes without touching the secret" do
      refute TOTP.verify(@secret, nil, at: 0)
      refute TOTP.verify(@secret, "", at: 0)
      refute TOTP.verify(@secret, "12345", at: 0)
      refute TOTP.verify(@secret, "1234567", at: 0)
      refute TOTP.verify(@secret, "abcdef", at: 0)
      assert TOTP.verify(@secret, " 702218 ", at: 0), "whitespace is trimmed (python parity)"
    end
  end

  describe "secret + uri generation" do
    test "generates unpadded base32 secrets" do
      secret = TOTP.generate_secret()
      assert String.length(secret) == 32
      refute String.contains?(secret, "=")
      assert {:ok, _} = Base.decode32(secret, padding: false)
    end

    test "provisioning uri matches the python format" do
      uri = TOTP.provisioning_uri(@secret, "admin", "Orbit Dashboard")

      assert uri ==
               "otpauth://totp/Orbit%20Dashboard%3Aadmin?secret=#{@secret}" <>
                 "&issuer=Orbit%20Dashboard&algorithm=SHA1&digits=6&period=30"
    end
  end
end
