defmodule Orbit.Crypto.FernetTest do
  use ExUnit.Case, async: true

  alias Orbit.Crypto.Fernet

  # Cross-language vectors generated by python-cryptography (the exact library
  # the FastAPI backend uses for the *_enc columns). Regenerate with:
  #
  #   docker exec -i dashboard-backend-1 python - <<'EOF'
  #   import json, base64
  #   from cryptography.fernet import Fernet
  #   key = base64.urlsafe_b64encode(bytes(range(32)))
  #   f = Fernet(key)
  #   print(json.dumps({"key": key.decode(), "vectors": [
  #       {"plaintext": pt, "token": f.encrypt(pt.encode()).decode()}
  #       for pt in ["", "hello", "ümläut-秘密-🔥", "a"*300]]}, ensure_ascii=False))
  #   EOF
  @vectors_path Path.join(__DIR__, "fernet_vectors.json")
  @vectors @vectors_path |> File.read!() |> Jason.decode!()
  @key @vectors["key"]

  describe "python-cryptography interop" do
    test "decrypts every token produced by the python backend's library" do
      for %{"plaintext" => plaintext, "token" => token} <- @vectors["vectors"] do
        assert Fernet.decrypt!(token, @key) == plaintext
      end
    end
  end

  describe "roundtrip" do
    test "encrypt then decrypt returns the plaintext" do
      for plaintext <- ["", "secret", "ümläut-秘密-🔥", String.duplicate("x", 5_000)] do
        token = Fernet.encrypt(plaintext, @key)
        assert Fernet.decrypt!(token, @key) == plaintext
      end
    end

    test "tokens are spec-shaped (version 0x80, urlsafe base64)" do
      token = Fernet.encrypt("check", @key)
      assert {:ok, <<0x80, _rest::binary>>} = Base.url_decode64(token, padding: true)
    end
  end

  describe "failure modes" do
    test "wrong key fails, never returns garbage" do
      other_key = Base.url_encode64(:crypto.strong_rand_bytes(32))
      token = Fernet.encrypt("secret", @key)
      assert {:error, %Fernet.Error{}} = Fernet.decrypt(token, other_key)
    end

    test "tampered ciphertext fails the HMAC" do
      token = Fernet.encrypt("secret", @key)
      {:ok, raw} = Base.url_decode64(token, padding: true)
      # Flip one bit in the middle of the ciphertext.
      pos = div(byte_size(raw), 2)
      <<head::binary-size(^pos), byte, tail::binary>> = raw
      tampered = Base.url_encode64(<<head::binary, Bitwise.bxor(byte, 1), tail::binary>>)
      assert {:error, %Fernet.Error{}} = Fernet.decrypt(tampered, @key)
    end

    test "malformed inputs fail cleanly" do
      assert {:error, %Fernet.Error{}} = Fernet.decrypt("not-base64!!", @key)
      assert {:error, %Fernet.Error{}} = Fernet.decrypt(Base.url_encode64("short"), @key)
      assert {:error, %Fernet.Error{}} = Fernet.decrypt(Fernet.encrypt("x", @key), "bad-key")
    end
  end
end
