defmodule Orbit.Auth.Password do
  @moduledoc """
  Argon2id password hashing, compatible with the existing user rows.

  The Python backend hashes with argon2-cffi defaults (argon2id, v=19,
  m=65536, t=3, p=4 — PHC string format); `argon2_elixir` shares those
  defaults and verifies any PHC argon2 hash, so existing users keep logging
  in across the rewrite. Proven against hashes generated by the running
  backend in password_test.exs.
  """

  @spec hash(String.t()) :: String.t()
  def hash(password) when is_binary(password), do: Argon2.hash_pwd_salt(password)

  @spec verify(String.t(), String.t()) :: boolean()
  def verify(password, password_hash) when is_binary(password) and is_binary(password_hash) do
    Argon2.verify_pass(password, password_hash)
  rescue
    # Malformed/legacy hash strings must read as "wrong password", never crash
    # the login path or leak hash internals (mirrors backend security.py).
    _ -> false
  end

  @doc """
  Verify while always spending one Argon2 verification, even when the account
  does not exist (pass `nil`). Otherwise response latency becomes a
  username-enumeration oracle (mirrors backend `verify_password_constant_time`).
  """
  @spec verify_constant_time(String.t(), String.t() | nil) :: boolean()
  def verify_constant_time(password, nil) when is_binary(password) do
    Argon2.no_user_verify()
    false
  end

  def verify_constant_time(password, password_hash), do: verify(password, password_hash)
end
