defmodule OrbitWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :orbit

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_orbit_key",
    signing_salt: "aUgmQ03O",
    same_site: "Lax"
  ]

  # peer_data + x_headers feed the GeoGate on_mount hook (the socket macro
  # bypasses the plug pipeline, so the geo check must run in the socket).
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :x_headers, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :x_headers, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :orbit,
    gzip: not code_reloading?,
    only: OrbitWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :orbit
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # GUI reverse proxy (§18): a GUI-host request (<slug>.localhost /
  # gui-<slug>.<domain>) is handled here and halted; any other host passes
  # through. BEFORE the parsers so the request body reaches the firewall raw.
  plug OrbitWeb.GuiProxy

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # GeoIP gate (DR-G2): after Plug.Static (assets stay servable), before the
  # router — every dynamic route including client-WS upgrades is checked.
  plug OrbitWeb.Plugs.GeoIP
  plug OrbitWeb.Router
end
