#!/usr/bin/env python3
"""Generate the prod GUI-proxy Caddyfile (deterministic gui-<id> -> port).

One wildcard vhost handles every firewall: a per-Host `import` maps gui-<id> to
that instance's forwarder port (14400+id, a fixed convention). The snippet arg
(the port) is substituted at adapt time, so the TLS upstream stays a literal —
Caddy forbids a runtime placeholder in a scheme/TLS upstream. No runtime config or
regeneration is needed; a firewall works as soon as its forwarder is started by
POST /gui/open (else Caddy returns 502). See §18 / README.

Usage:
  python scripts/gen-gui-caddyfile.py [MAX_ID] > docker/Caddyfile.gui-prod

Caddy env vars (set on the Caddy service):
  ORBIT_GUI_DOMAIN    wildcard base, e.g. example.com  (origins gui-<id>.example.com)
  ORBIT_GUI_APP       app host:port for handoff/authcheck (default app:80)
  ORBIT_GUI_FWD_HOST  host the forwarders run on        (default app)
"""
from __future__ import annotations

import sys

MAX_ID = int(sys.argv[1]) if len(sys.argv) > 1 else 25
FORWARDER_BASE = 14400

head = """\
# GENERATED by scripts/gen-gui-caddyfile.py — do not edit by hand.
#
# Prod GUI proxy. An external Traefik terminates TLS and routes
# Host(*.{$ORBIT_GUI_DOMAIN}) here over HTTP; this Caddy host-matches gui-<id>,
# gates on the orbit_gui cookie (forward_auth), and proxies to that instance's
# in-container forwarder (TLS to the firewall through the agent tunnel).
{
	auto_https off
}

# One vhost body, parameterised by the forwarder port (substituted at adapt time).
(gui_vhost) {
	# Token handoff + authcheck go to the app (backend), NOT the firewall.
	@orbit path /__orbit/*
	handle @orbit {
		rewrite * /api/gui/handoff?{query}
		reverse_proxy {$ORBIT_GUI_APP:app:80}
	}
	# Gate on the orbit_gui cookie (authcheck derives the instance from the
	# X-Forwarded-Host gui-<id>), then proxy to that instance's forwarder.
	handle {
		forward_auth {$ORBIT_GUI_APP:app:80} {
			uri /api/gui/authcheck
		}
		reverse_proxy {$ORBIT_GUI_FWD_HOST:app}:{args[0]} {
			transport http {
				tls
				tls_insecure_skip_verify
			}
		}
	}
}

http://*.{$ORBIT_GUI_DOMAIN} {
"""

out = [head]
for i in range(1, MAX_ID + 1):
    out.append(f"\t@gui-{i} host gui-{i}.{{$ORBIT_GUI_DOMAIN}}\n")
    out.append(f"\thandle @gui-{i} {{\n\t\timport gui_vhost {FORWARDER_BASE + i}\n\t}}\n")
out.append("}\n")
sys.stdout.write("".join(out))
